---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp-all-deployment
spec:
  selector:
    matchLabels:
      app: bootcamp
  replicas: 2
  template:
    metadata:
      labels:
        app: bootcamp
    spec:
      containers:
        - name: bootcamp
          image: docker.io/jocatalin/kubernetes-bootcamp:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bootcamp-all-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bootcamp